name: CI - Build and deploy

on:
  push:
    branches: [ master, main ]


permissions:
  contents: write


jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
      - name: Install dependencies
        run: bundle install
      - name: Build
        run: bundle exec rake site:build
      - name: Prepare build environment
        run: |
          rm -rf build/.git
          cp CNAME build/
          SHA=$(git rev-parse $(git log -1 --pretty=format:%h))
          echo Updating to mjafarmashhadi/mjafarmashhadi.github.io@$SHA. > build/COMMIT_MESSAGE
      - name: Store build files
        uses: actions/upload-artifact@v4
        with:
          name: website-artifacts
          path: build/
          compression-level: 
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Get the built package
      uses: actions/download-artifact@v4
      with:
        name: website-artifacts
        path: .
    - name: Configure git ad commit changes
      run: |
        git config user.name $GIT_NAME
        git config user.email $GIT_EMAIL
        git config pager.branch false
        git config push.default simple
        COMMIT_MESSAGE=$(cat COMMIT_MESSAGE)
        rm COMMIT_MESSAGE
        git add .
        git commit -m "$COMMIT_MESSAGE"
      env:
        GIT_NAME: MJafarMashhadi
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    - name: Push to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
