name: CI - Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ 'closed' ]
    branches: [ master ]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - id: s0
        name: Checkout
        uses: actions/checkout@v2
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
      - name: Install Node
        uses: actions/setup-node@v2
        if: steps.s0.outcome == 'success'
        with:
          node-version: '15.x'
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        if: steps.s0.outcome == 'success'
        with:
          ruby-version: '^2.5.1'
      - name: Install dependencies
        run: bundle install
        if: steps.s0.outcome == 'success'
      - name: Build
        if: steps.s0.outcome == 'success'
        run: bundle exec rake site:build
      - name: Prepare build environment
        if: steps.s0.outcome == 'success'
        run: |
          rm -rf build/.git
          cp CNAME build/
          SHA=$(git rev-parse $(git log -1 --pretty=format:%h))
          echo Updating to mjafarmashhadi/mjafarmashhadi.github.io@$SHA. > build/COMMIT_MESSAGE
      - name: Store build files
        uses: actions/upload-artifact@v2
        if: steps.s0.outcome == 'success'
        with:
          name: website-artifacts
          path: build/
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Get the built package
      uses: actions/download-artifact@v2
      with:
        name: website-artifacts
        path: .
    - name: Configure git ad commit changes
      run: |
        git config user.name $GIT_NAME
        git config user.email $GIT_EMAIL
        git config pager.branch false
        git config push.default simple
        COMMIT_MESSAGE=$(cat COMMIT_MESSAGE)
        rm COMMIT_MESSAGE
        git add .
        git commit -m "$COMMIT_MESSAGE"
      env:
        GIT_NAME: MJafarMashhadi
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    - name: Push to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
